"""Unified analysis schema — every investigation record this project stores.

``schema_version`` is stamped on every record so old analyses stay readable
after the schema evolves. Each section of the investigation file is a card
with exactly one explicit state:

    loading | ok | not_applicable | skipped | error

Rules enforced by :func:`validate_analysis` (project constant #4):

* no section may carry a value without a real source — builders here only
  shape data, they never invent it,
* ``skipped`` always carries a human-readable ``reason``,
* ``error`` always carries an ``error`` message,
* the verdict card may only carry a label from the fixed set, and when its
  state is ``ok`` its ``why_rule`` / ``reasoning`` must be present (they are
  generated by the verdict engine from rules, never hand-written).

This module is intentionally data-only: no model code, no network, no
side effects. Producers fill sections phase by phase (m2 engine, m3
forensics, m4 scores, m5 search, m7 assembly); the validator is the contract
they all must satisfy.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import uuid

SCHEMA_VERSION = "1.0"

SECTION_STATES = ("loading", "ok", "not_applicable", "skipped", "error")
MODEL_STATUSES = ("ok", "error", "skipped")

VERDICT_LABELS = ("AI Detected", "Possible Edits", "Investigate", "No AI Detected")

AXIS_IDS = ("ai_generation", "editing_check", "source_check")
AXIS_LABELS = {
    "ai_generation": ("AI Generation", "التوليد بالذكاء الاصطناعي"),
    "editing_check": ("Editing Check", "فحص التعديل"),
    "source_check": ("Source Check", "فحص المصدر"),
}

# UI cards that carry their payload elsewhere (verdict / technical_info /
# models / pipeline keep their state inline); everything below is a pure
# section card stored in ``sections``.
SECTION_IDS = (
    "spot_the_difference",
    "whats_in_image",
    "c2pa",
    "what_to_do_next",
    "links_on_web",
    "fact_check_monitor",
    "reverse_search",
    "location",
    "further_investigation",
    "how_we_know",
    "ask_about_image",
    "was_this_result_correct",
    "ai_visual_findings",
    "model_scores",
    "manipulation_map",
    "what_the_computer_sees",
    "pipeline",
)


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def new_section(
    state: str = "loading",
    *,
    reason: Optional[str] = None,
    error: Optional[str] = None,
    data: Any = None,
) -> Dict[str, Any]:
    """A section card in one of the five explicit states."""
    if state not in SECTION_STATES:
        raise ValueError(f"invalid section state: {state!r}")
    section: Dict[str, Any] = {"state": state}
    if reason is not None:
        section["reason"] = reason
    if error is not None:
        section["error"] = error
    if data is not None:
        section["data"] = data
    return section


def new_axis(axis_id: str) -> Dict[str, Any]:
    if axis_id not in AXIS_IDS:
        raise ValueError(f"unknown axis id: {axis_id!r}")
    return {
        "id": axis_id,
        "label_en": AXIS_LABELS[axis_id][0],
        "label_ar": AXIS_LABELS[axis_id][1],
        "state": "loading",
        "summary": None,
    }


def new_analysis(
    *,
    name: str,
    sha256: Optional[str] = None,
    size_bytes: Optional[int] = None,
    width: Optional[int] = None,
    height: Optional[int] = None,
    format: Optional[str] = None,
) -> Dict[str, Any]:
    """A fresh, fully-empty analysis record: every card starts in 'loading'."""
    return {
        "schema_version": SCHEMA_VERSION,
        "id": uuid.uuid4().hex,  # random, not guessable (share links)
        "created_at": datetime.now(timezone.utc).isoformat(),
        "image": {
            "name": name,
            "sha256": sha256,
            "size_bytes": size_bytes,
            "width": width,
            "height": height,
            "format": format,
        },
        "verdict": {
            "state": "loading",
            "label": None,
            "confidence": None,
            "axes": [new_axis(a) for a in AXIS_IDS],
            "why_rule": None,
            "reasoning": None,
            "human_line": None,
            "disagreement": [],
        },
        "models": [],        # per-model entries: {id, kind, status, ...}
        "forensics": {"state": "loading", "checks": []},
        "external": {
            "state": "loading",
            "web_presence": {"state": "loading"},
            "fact_check": {"state": "loading"},
            "links": {"state": "loading"},
            "location": {"state": "loading"},
        },
        "pipeline": [],      # ordered steps: {name, status, duration_ms, summary}
        "technical_info": {"state": "loading"},
        "sections": {sid: new_section("loading") for sid in SECTION_IDS},
    }


# ---------------------------------------------------------------------------
# Mutation helpers (state discipline lives here, not in callers)
# ---------------------------------------------------------------------------

def set_section(
    record: Dict[str, Any],
    section_id: str,
    state: str,
    *,
    reason: Optional[str] = None,
    error: Optional[str] = None,
    data: Any = None,
) -> Dict[str, Any]:
    """Replace one section card (validating the state)."""
    if section_id not in record["sections"]:
        raise KeyError(f"unknown section: {section_id}")
    section = new_section(state, reason=reason, error=error, data=data)
    record["sections"][section_id] = section
    return section


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _check_state(container: Dict[str, Any], where: str, errors: List[str]) -> None:
    state = container.get("state")
    if state not in SECTION_STATES:
        errors.append(f"{where}: invalid state {state!r}")
        return
    if state == "skipped" and not container.get("reason"):
        errors.append(f"{where}: skipped state requires a reason")
    if state == "error" and not container.get("error"):
        errors.append(f"{where}: error state requires an error message")


def _check_status(container: Dict[str, Any], where: str, errors: List[str]) -> None:
    """Same rules as _check_state but for entries keyed 'status' (checks)."""
    status = container.get("status")
    if status not in SECTION_STATES:
        errors.append(f"{where}: invalid status {status!r}")
        return
    if status == "skipped" and not container.get("reason"):
        errors.append(f"{where}: skipped status requires a reason")
    if status == "error" and not container.get("error"):
        errors.append(f"{where}: error status requires an error message")


def validate_analysis(record: Any) -> List[str]:
    """Return a list of contract violations (empty == valid)."""
    errors: List[str] = []
    if not isinstance(record, dict):
        return ["record is not a dict"]

    if record.get("schema_version") != SCHEMA_VERSION:
        errors.append(
            f"schema_version must be {SCHEMA_VERSION!r}, got {record.get('schema_version')!r}"
        )
    if not record.get("id"):
        errors.append("missing id")
    if not record.get("created_at"):
        errors.append("missing created_at")

    image = record.get("image")
    if not isinstance(image, dict) or not image.get("name"):
        errors.append("image must be an object with at least a name")

    # ---- verdict card ----
    verdict = record.get("verdict")
    if not isinstance(verdict, dict):
        errors.append("verdict must be an object")
    else:
        _check_state(verdict, "verdict", errors)
        axes = verdict.get("axes")
        if not isinstance(axes, list) or [a.get("id") for a in axes if isinstance(a, dict)] != list(AXIS_IDS):
            errors.append(f"verdict.axes must list exactly {list(AXIS_IDS)} in order")
        else:
            for axis in axes:
                if axis.get("state") not in SECTION_STATES:
                    errors.append(f"verdict axis {axis.get('id')}: invalid state {axis.get('state')!r}")
        if verdict.get("state") == "ok":
            label = verdict.get("label")
            if label not in VERDICT_LABELS:
                errors.append(f"verdict.label must be one of {list(VERDICT_LABELS)}, got {label!r}")
            if not verdict.get("why_rule"):
                errors.append("verdict.ok requires why_rule (generated by the engine)")
            if not verdict.get("reasoning"):
                errors.append("verdict.ok requires reasoning")

    # ---- models ----
    models = record.get("models")
    if not isinstance(models, list):
        errors.append("models must be a list")
    else:
        for i, model in enumerate(models):
            if not isinstance(model, dict):
                errors.append(f"models[{i}] must be an object")
                continue
            if not model.get("id"):
                errors.append(f"models[{i}] missing id")
            if not model.get("kind"):
                errors.append(f"models[{i}] missing kind")
            status = model.get("status")
            if status not in MODEL_STATUSES:
                errors.append(f"models[{i}]: invalid status {status!r}")
            elif status == "ok":
                prob = model.get("prob_fake")
                if not isinstance(prob, (int, float)) or isinstance(prob, bool) or not (0.0 <= prob <= 1.0):
                    errors.append(f"models[{i}]: status ok requires prob_fake in [0, 1]")
            elif status == "skipped" and not model.get("reason"):
                errors.append(f"models[{i}]: skipped requires a reason")
            elif status == "error" and not model.get("error"):
                errors.append(f"models[{i}]: error requires an error message")

    # ---- forensics ----
    forensics = record.get("forensics")
    if not isinstance(forensics, dict):
        errors.append("forensics must be an object")
    else:
        _check_state(forensics, "forensics", errors)
        checks = forensics.get("checks")
        if not isinstance(checks, list):
            errors.append("forensics.checks must be a list")
        else:
            for i, check in enumerate(checks):
                if not isinstance(check, dict) or not check.get("id"):
                    errors.append(f"forensics.checks[{i}] must be an object with id")
                    continue
                _check_status(check, f"forensics.checks[{i}] ({check.get('id')})", errors)

    # ---- external ----
    external = record.get("external")
    if not isinstance(external, dict):
        errors.append("external must be an object")
    else:
        _check_state(external, "external", errors)
        for sub in ("web_presence", "fact_check", "links", "location"):
            sub_obj = external.get(sub)
            if not isinstance(sub_obj, dict):
                errors.append(f"external.{sub} must be an object")
            else:
                _check_state(sub_obj, f"external.{sub}", errors)

    # ---- pipeline ----
    pipeline = record.get("pipeline")
    if not isinstance(pipeline, list):
        errors.append("pipeline must be a list")
    else:
        for i, step in enumerate(pipeline):
            if not isinstance(step, dict) or not step.get("name"):
                errors.append(f"pipeline[{i}] must be an object with name")
                continue
            if step.get("status") not in SECTION_STATES:
                errors.append(f"pipeline[{i}]: invalid status {step.get('status')!r}")

    # ---- technical info ----
    tech = record.get("technical_info")
    if not isinstance(tech, dict):
        errors.append("technical_info must be an object")
    else:
        _check_state(tech, "technical_info", errors)

    # ---- sections ----
    sections = record.get("sections")
    if not isinstance(sections, dict):
        errors.append("sections must be a dict")
    else:
        for sid in SECTION_IDS:
            if sid not in sections:
                errors.append(f"missing section: {sid}")
        for sid, section in sections.items():
            if sid not in SECTION_IDS:
                errors.append(f"unknown section: {sid}")
                continue
            if not isinstance(section, dict):
                errors.append(f"section {sid} must be an object")
                continue
            _check_state(section, f"sections.{sid}", errors)

    return errors


def is_valid(record: Any) -> bool:
    return not validate_analysis(record)


__all__ = [
    "SCHEMA_VERSION",
    "SECTION_STATES",
    "MODEL_STATUSES",
    "VERDICT_LABELS",
    "AXIS_IDS",
    "AXIS_LABELS",
    "SECTION_IDS",
    "new_section",
    "new_axis",
    "new_analysis",
    "set_section",
    "validate_analysis",
    "is_valid",
]
